# Constants Section
ENV_FILE = '.env'
DOCKER_IMAGE = 'naeural/edge_node'
DOCKER_CONTAINER_NAME = 'edge_node_container'
WINDOWS_VOLUME_PATH = '\\\\wsl.localhost\\docker-desktop-data\\data\\docker\\volumes\\naeural_vol\\_data'
LINUX_VOLUME_PATH = '/var/lib/docker/volumes/naeural_vol/_data'
LOCAL_HISTORY_FILE = '_data/local_history.json'
E2_PEM_FILE = '_data/e2.pem'
LOCAL_ADDRESS_FILE = '_data/local_address.txt'
WINDOW_TITLE = 'Edge Node Manager'
EDIT_ENV_BUTTON_TEXT = 'Edit .env File'
LAUNCH_CONTAINER_BUTTON_TEXT = 'Launch Container'
STOP_CONTAINER_BUTTON_TEXT = 'Stop Container'
DELETE_AND_RESTART_BUTTON_TEXT = 'Delete e2.pem and Restart Container'
LOCAL_NODE_ADDRESS_LABEL_TEXT = 'Local Node Address'
REFRESH_LOCAL_ADDRESS_BUTTON_TEXT = 'Refresh Local Address'
COPY_ADDRESS_BUTTON_TEXT = 'Copy Address'
