name: Multi-step multi-platform build on PR to main branch and saves the artifacts

on:
  pull_request:
    branches: ["main"]

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check-version.outputs.should-run }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Get latest release version
        id: latest-version
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Check version in ver.py
        id: check-version
        run: |
          CURRENT_VERSION=$(cat ver.py | grep -o "'.*'")
          echo "Current version is $CURRENT_VERSION"

          if [ "$CURRENT_VERSION" == "$LATEST_TAG" ]; then
            echo "Version $CURRENT_VERSION has not been incremented vs already released $LATEST_TAG. Build will be cancelled."
            echo "::set-output name=should-run::false"
            exit 1
          else
            echo "Current version $CURRENT_VERSION differs from latest tag $LATEST_TAG. Build will continue."
            echo "::set-output name=should-run::true"
          fi

  build:
    needs: check-version
    if: needs.check-version.outputs.should-run == 'true'

    strategy:
      matrix:
        include:
          - os: windows-latest
            build: ./build_scripts/win32_build.bat
            name: EdgeNodeLauncher-WIN32
            platformDependencies: ""

#          - os: ubuntu-24.04
#            build: |
#              chmod +x build_scripts/unix_build.sh
#              ./build_scripts/unix_build.sh
#            name: EdgeNodeLauncher-LINUX_Ubuntu-24.04
#            platformDependencies: sudo apt-get update && sudo apt install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev --fix-missing
#
#          - os: ubuntu-22.04
#            build: |
#              chmod +x build_scripts/unix_build.sh
#              ./build_scripts/unix_build.sh
#            name: EdgeNodeLauncher-LINUX_Ubuntu-22.04
#            platformDependencies: sudo apt-get update && sudo apt install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev --fix-missing
#
#          - os: ubuntu-20.04
#            build: |
#              chmod +x build_scripts/unix_build.sh
#              ./build_scripts/unix_build.sh
#            name: EdgeNodeLauncher-LINUX_Ubuntu-20.04
#            platformDependencies: sudo apt-get update && sudo apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev --fix-missing

    name: Build installers ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.11"
      - run: ${{ matrix.platformDependencies }}
      - name: Setup env
        run: |
          pip install -r requirements.txt
          pip3 install --upgrade PyInstaller pyinstaller-hooks-contrib

      - name: Build app
        run: ${{ matrix.build }}

      - name: Check path
        if: runner.os == 'Windows'
        run: |
          ls         
          pwd
          ls  dist
          ls build
          mkdir -p ./signed
          ls  ${{ github.workspace }}/dist
#          dir  ${{ github.workspace }}/dist

#      - name: Unlock Windows Executable
#        if: runner.os == 'Windows'
#        run: |
#          tasklist | findstr /I "EdgeNodeLauncher.exe" && taskkill /F /IM EdgeNodeLauncher.exe || echo "No process running"

#      - name: Set Permissions for Signing
#        if: runner.os == 'Windows'
#        run: |
#          icacls build\EdgeNodeLauncher.exe /grant Everyone:F /T /C
#

#      - name: Wait for File Unlock
#        if: runner.os == 'Windows'
#        run: timeout /t 5

#      - name: Debug File Path
#        if: runner.os == 'Windows'
#        run: |
#          echo "Checking file path..."
#          dir build
#          dir ${{ github.workspace }}/build
#      - name: Set Permissions for Signing
#        if: runner.os == 'Windows'
#        run: |
#          icacls build\EdgeNodeLauncher.exe /grant Everyone:F /T /C
#          attrib -r build\EdgeNodeLauncher.exe
      - name: Sign Windows app
        if: runner.os == 'Windows'
        uses: sslcom/esigner-codesign@develop
        with:
          # Sign and timestamp code object.
          command: sign
          # SSL.com account username
          username: {{ secrets.SSL_USERNAME }}
          # SSL.com account password.
          password: {{ secrets.SSL_PASSWORD }}
          # Credential ID for signing certificate.
          credential_id: {{ secrets.SSL_CREDENTIAL_ID }}
          # OAuth TOTP Secret (https://www.ssl.com/how-to/automate-esigner-ev-code-signing)
          totp_secret: {{ secrets.SSL_TOTP_SECRET }}
          # Path of code object to be signed. (DLL, JAR, EXE, MSI files vb... )
          file_path: ${{ github.workspace }}/dist/EdgeNodeLauncher.exe
          # Directory where signed code object(s) will be written.
          output_path: ${{ github.workspace }}/signed
          # Scan code before sign
          malware_block: false
          # Environment Name, For Production 'PROD' or For Staging 'TEST'
          environment_name: TEST

      - name: Replace non-signed version with signed one
        if: runner.os == 'Windows'
        run: |
          rm dist/EdgeNodeLauncher.exe
          mv signed/EdgeNodeLauncher.exe dist/EdgeNodeLauncher.exe


#        env:
#          ES_USERNAME: "Naeural999"
#          ES_PASSWORD: "romaniaA1!@"
#          CREDENTIAL_ID: ""
#          ES_TOTP_SECRET: ""



#        run: |
#          $filePath = "utils/const.py"
#          (Get-Content $filePath) -replace '\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*', "${{ env.MQTT_K }}" | Set-Content $filePath

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-build-${{ github.event.pull_request.number }}-${{ github.sha }}
          path: dist/*

  collect-artifacts:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: EdgeNodeLauncher-WIN32-build-${{ github.event.pull_request.number }}-${{ github.sha }}
          path: ./all-builds/EdgeNodeLauncher-WIN32-signed

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: EdgeNodeLauncher-LINUX_Ubuntu-24.04-build-${{ github.event.pull_request.number }}-${{ github.sha }}
          path: ./all-builds/EdgeNodeLauncher-LINUX_Ubuntu-24.04

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: EdgeNodeLauncher-LINUX_Ubuntu-22.04-build-${{ github.event.pull_request.number }}-${{ github.sha }}
          path: ./all-builds/EdgeNodeLauncher-LINUX_Ubuntu-22.04

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: EdgeNodeLauncher-LINUX_Ubuntu-20.04-build-${{ github.event.pull_request.number }}-${{ github.sha }}
          path: ./all-builds/EdgeNodeLauncher-LINUX_Ubuntu-20.04
